### ISSUE TITLE
Çıkış pinlerini değiştirmek mümkün mü?

### ISSUE THREAD

**Issue by uguraltinsoy** [barisdinc/LibAPRS_Tracker#1]
Merhaba. Çıkış pinlerini değiştirmek mümkün mü? ve devre şemasını paylaşırmısın

**Comment by barisdinc** [comment]
mumkun ama kutuphanenin icine bakman lazim.. yanlis hatirlamiyorsam kutuphanede BIT SHIFTIONG yapiyordum bir yerlerde.., bir firsatim olunca baklarim tekrar
