### ISSUE TITLE
questions: repository is alive?

### ISSUE THREAD

**Issue by richonguzman** [barisdinc/LibAPRS_Tracker#2]
Hi,

is this still working? I can't find a tutorial or steps to follow this completely and achieve the working Arduino Nano to send APRS packets

is there a way to contact you through mail, telegram, WhatsApp or else for just a little guidance? 

Greetings from Chile

**Comment by barisdinc** [comment]
my email is barisdinc gmail.com
You can contact me via email..
I will be happy to answer your questions

Baris DINC
TA7W / OH2UDS
